name: Build, Scan, and Push Docker image to ECR
on:
  workflow_dispatch:
  
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'kubernetes/**'

jobs:
  build-and-push:
    name: Build, Scan, and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get current time
        id: time
        run: echo "::set-output name=date::$(TZ=Asia/Kolkata date "+%Y-%m-%d-%H-%M")"

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nidhin-nodejs-application
          IMAGE_TAG: ${{ steps.time.outputs.date }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:nidhin-nodejs-application-$IMAGE_TAG .
          docker images
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:nidhin-nodejs-application-$IMAGE_TAG

      - name: Clean working directory
        run: git clean -fdX


      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
